### ISSUE TITLE
Vault and TACACS+ not functioning after intial installation

### ISSUE THREAD

**Issue by jsmith7735** [eNMS-automation/eNMS#316] opened 2021-03-13 22:12 UTC
I modified the settings.json file on the local machine to add the TACACS+ address and the enable flag. I also set the environment variable using the system service configuration. When I try to log in via these are the log messages that I am noticing. I also did tcpdump to look for outbound packets on TCP/49 . This did not return any results. Based on the log and the lack of packets going out I believe there is an issue on the eNMS side.

Mar 13 21:52:59 cersrenms01 gunicorn[37420]: [2021-03-13 21:52:59 +0000] [37420] [DEBUG] POST /login
Mar 13 21:52:59 cersrenms01 gunicorn[37420]: 2021-03-13 21:52:59,053 WARNING  Authentication error for user 'myusername' (name 'TACACSClient' is not defined)

When I change the settings.json file to enable vault, the eNMS application fails to load. I receive the error messages below.
Mar 13 22:08:54 cersrenms01 gunicorn[38435]:     from eNMS.server import server as app  # noqa: F401
Mar 13 22:08:54 cersrenms01 gunicorn[38435]:   File "/var/www/eNMS/eNMS/__init__.py", line 3, in <module>
Mar 13 22:08:54 cersrenms01 gunicorn[38435]:     app = App()
Mar 13 22:08:54 cersrenms01 gunicorn[38435]:   File "/var/www/eNMS/eNMS/controller/base.py", line 74, in __init__
Mar 13 22:08:54 cersrenms01 gunicorn[38435]:     self.init_vault_client()
Mar 13 22:08:54 cersrenms01 gunicorn[38435]:   File "/var/www/eNMS/eNMS/controller/base.py", line 329, in init_vault_client
Mar 13 22:08:54 cersrenms01 gunicorn[38435]:     self.vault_client = VaultClient(url=url, token=getenv("VAULT_TOKEN"))
Mar 13 22:08:54 cersrenms01 gunicorn[38435]: NameError: name 'VaultClient' is not defined
Mar 13 22:08:54 cersrenms01 systemd[1]: enms.service: Main process exited, code=exited, status=1/FAILURE
Mar 13 22:08:54 cersrenms01 systemd[1]: enms.service: Failed with result 'exit-code'.

I can seal and unseal the vault manually. I used the Hashicorp installation instructions to install and setup the Vault server.

**Comment by afourmy** [comment] 2021-03-15 10:49
looks like the tacacs library is not installed. there should be an error message when you start eNMS telling you that the import failed ?

**Comment by jsmith7735** [comment] 2021-03-15 22:07
@afourmy 

Thanks for the response. I installed the optional requirements and it does appear as the TACACS+ may be working now. I have to define the TACACS user and password in the database of eNMS. Is this the intended behavior? I would expect that eNMS would authenticate against the TACACS+ server. If this is the case then I can consider the TACACS issue resolved.

I still receive the same error for Vault after the installation of the optional python packages.

**Comment by afourmy** [comment] 2021-03-16 17:26
> I have to define the TACACS user and password in the database of eNMS. Is this the intended behavior?

no the intended behavior is to query the tacacs+ server... are you selecting tacacs in the login page ?

> I am now receiving the error listed below.

looks like the VAULT_TOKEN env variable is not defined, or maybe the version of the vault is too old, I'm not sure.

**Comment by afourmy** [comment] 2021-03-18 09:26
closing as this is an environment issue, not a bug in eNMS

**Closed by afourmy** 2021-03-18 09:26 UTC
Labels: question
